[tool.poetry]
name = "miml"
version = "0.1.0"
description = "Multi Instance Multi Label Image Classification"
authors = ["Mridula Maddukuri"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
